# Site settings
title: Bruno Meira Melhado
email: bruno.meiramelhado@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://meirabruno.github.io" # the base hostname & protocol for your site
twitter_username: brunomeira
github_username:  meirabruno
permalink: /:title:output_ext

# Build settings
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass