# Site settings
title: Bruno Meira Melhado
email: bruno.meiramelhado@gmail.com
description: "Playing with ruby everyday, learning about ruby, rails, rspec, js, css, tdd. Getting connected with whats happening on ruby and rails comunity."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://meirabruno.github.io" # the base hostname & protocol for your site
twitter_username: brunomeira
github_username:  meirabruno
permalink: /:title:output_ext

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass